<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.addToCart</name>
   <tag></tag>
   <elementGuidId>fb5ac78e-cd8c-41f9-b6c8-b94d32728651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.addToCart&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.addToCart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>964b2cde-9861-4e93-9c17-117f606b0e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b0d71c4d-7c26-46c4-b3eb-e091b88fd3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.addToCart</value>
      <webElementGuid>22327b23-2504-4e1b-9a86-8adb85ea27d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asins</name>
      <type>Main</type>
      <value>[&quot;0385504209&quot;,&quot;0743486226&quot;,&quot;0385504225&quot;]</value>
      <webElementGuid>4cd8808d-f437-4f6e-b4a3-c072b4d9cf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mix-operations</name>
      <type>Main</type>
      <value>AddToCart</value>
      <webElementGuid>9488fbe4-4fc3-47ab-99f9-cf4b869b9a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-numitems</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>56e7e387-4b2e-4608-beb3-6f296633e37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reftag</name>
      <type>Main</type>
      <value>pd_bxgy_crt</value>
      <webElementGuid>94807c4f-4108-4a9c-bec9-d2455b774f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=pd_bxgy_crt?_encoding=UTF8&amp;pd_rd_w=BcfqT&amp;content-id=amzn1.sym.839d7715-b862-4989-8f65-c6f9502d15f9&amp;pf_rd_p=839d7715-b862-4989-8f65-c6f9502d15f9&amp;pf_rd_r=BQ0W9ESVKBS3GWVBJCMP&amp;pd_rd_wg=5kZf8&amp;pd_rd_r=9f645404-9dbf-4bb6-9abd-e414d2153950</value>
      <webElementGuid>606b58c6-25eb-4c37-859e-4dada0e7645b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>6b8bb102-d749-4a02-ae31-c3d25c1a3766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-7-announce</value>
      <webElementGuid>8ad91eef-e64c-444c-829f-b43fe615c9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-7&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>95754f4d-cad0-46cb-b926-353e3c5c26e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.addToCart']</value>
      <webElementGuid>aa65477b-00a3-440f-be76-b6ad09d16228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-7']/span/input</value>
      <webElementGuid>582436dd-9f58-4396-a5c6-5ec505bc6f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/input</value>
      <webElementGuid>3a5b1352-b880-4804-ae48-ddb5e3e0bee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit.addToCart']</value>
      <webElementGuid>d21fd9c9-05a2-4d44-84b1-88a00b571afa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
